### ISSUE TITLE
Will this library fully support strict types?

### ISSUE THREAD

**Issue by PeeHaa** [ekinhbayar/IntervalParser#10]
I see that the base exception declares strict types, but the other classes don't.

Will this library require strict types internally?

**Comment by ekinhbayar** [comment]
Although I'm not entirely sure whether it really should because of [this](http://stackoverflow.com/a/32943651/2852427), it will require strict types, at least for now unless anyone thinks it's really better without it.

I've been moving stuff a lot lately so pretty sure there are mistakes/missing stuff. I'll add in the directive to where I see missing in a minute. Feel free to add in any missing bits or modify anything you think would be an improvement  :-)

**Comment by ekinhbayar** [comment]
For now I am closing this issue. Anyone who would like to say something can surely ping and I can reopen :-)
